config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  
  # root route
  root "pages#index"

  # devise routes
  devise_for :employees, module: "employees", skip: [:registerations, :confirmations, :omniauth_callbacks] 
  as :employee do 
    get 'employee/edit/:id', to: "employees/registrations#edit", as: 'employee_registration_edit'
    patch '/employees/edit/:id', to: 'employees/registrations#update', as: 'employee_update'
    put '/employees/edit/:id', to: 'employees/registrations#update'

    get 'employee/profile/edit/:id', to: "employees/registrations#edit_profile", as: 'employee_registration_profile_edit'
    patch '/employees/profile/edit/:id', to: 'employees/registrations#update_profile', as: 'employee_profile_update'
    put '/employees/profile/edit/:id', to: 'employees/registrations#update_profile'
  end  

  # get routes
  get '/employee', to: "pages#dashboard", :as => :employee_root
  get '/employee/list', to: "pages#show", as: 'employees_list'

  get '/employee/division/new', to: "divisions#new", as: 'division_new'
  get '/employee/division/index', to: "divisions#index", as: 'division_index'
  get '/employee/division/edit/:id', to: 'divisions#edit', as: 'division_edit'
  get '/employee/division/show/:id', to: "divisions#show", as: 'division' 

  get '/employee/designation/new', to: "designations#new", as: 'designation_new'
  get '/employee/designation/index', to: "designations#index", as: 'designation_index'
  get '/employee/designation/edit/:id', to: 'designations#edit', as: 'designation_edit' 
  get '/employee/designation/show/:id', to: "designations#show", as: 'designation'

  get '/employee/project/new', to: "projects#new", as: 'project_new'
  get '/employee/project/index', to: "projects#index", as: 'project_index'
  get '/employee/project/edit/:id', to: "projects#edit", as: 'project_edit'
  get '/employee/project/show/:id', to: "projects#show", as: 'project' 
  get 'employee/project/assign/:id', to: "projects#assign_to_project", as: 'project_assign'
  get 'employee/project/remove/:id', to: "projects#remove_from_project", as: 'project_remove'

  # post put patch routes
  post 'designations', to: 'designations#create'
  patch '/designations/:id', to: 'designations#update', as: 'designation_update'
  put '/designations/:id', to: 'designations#update'

  post 'divisions', to: 'divisions#create'
  patch  '/divisions/:id', to: 'divisions#update', as: 'division_update'
  put   '/divisions/:id', to: 'divisions#update'

  post 'projects', to: 'projects#create'
  patch  '/projects/:id', to: 'projects#update', as: 'project_update'
  put   '/projects/:id', to: 'projects#update'
  post 'projects/assign/:id', to: 'projects#assign', as: 'project_assign_to' 

  # delete routes
  delete 'projects/remove/:id', to: 'projects#remove', as: 'project_remove_from'

end

app/models/designation.rb
class Designation < ApplicationRecord

    ## Validations
    validates :name, presence: true, length: { minimum: 2, maximum: 50 }, uniqueness: { case_sensitive: false }

    ## Associations
    has_many :employees

end   

app/controllers/designations_controller.rb
class DesignationsController < ApplicationController
    before_action :identify_employee

    def index 
        @designations = Designation.all
    end 

    def show 
        @designation = Designation.find(params[:id])
    end    

    def new 
        @designation = Designation.new
    end    

    def create 
        @designation = Designation.new(params.require(:designation).permit(:name))
        if @designation.save
            flash[:notice] = "Designation was successfully created."
            redirect_to designation_path(@designation)
        else 
            render 'new'    
        end    
    end    

    def edit 
        @designation = Designation.find(params[:id])
    end    

    def update 
        @designation = Designation.new(params.require(:designation).permit(:name))
        if @designation.update
            flash[:notice] = "Designation was successfully updated."
            redirect_to designation_path(@designation)
        else 
            render 'edit'    
        end 
    end    

    private

    def identify_employee 
        unless current_employee.master_role.name == "HR Manager"
            flash[:alert] = "You do not have access to this section" 
            redirect_to employee_root_path 
        end 
    end    

end    

app/views/designations/edit.html.erb
<div style="background-image: url(<%=asset_url('annie-spratt-FSFfEQkd1sc-unsplash.jpg')%>);background-size: cover;height: 100vh;">
<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
    <div class="container-fluid">
      <div class="navbar-brand">Employee Portal</div>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="https://www.paychex.com">Details</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>   

<div class="container">
<div class="p-5 rounded-lg m-3", style="background: rgba(255, 255, 255, 0.8)">
<center>
<h1>Create New Designation</h1> <br/>

<%= form_with model: @designation, local: true do |f| %>
    <p>
        <%= f.label :name %><br/>
        <%= f.text_field :name %>
    </p>  

    <p>
        <%= f.submit %>
    </p>
<% end %> 

</center>
<center><p><a href="<%= designation_index_path %>" class="btn btn-outline-primary">Cancel</a></p></center>
</div>
</div>
</div>

app/views/designations/index.html.erb
<div style="background-image: url(<%=asset_url('annie-spratt-FSFfEQkd1sc-unsplash.jpg')%>);background-size: cover;height: 100vh;">
<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
  <div class="container-fluid">
    <div class="navbar-brand">Employee Portal</div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" id="navbarDropdown" data-bs-toggle="dropdown" aria-expanded="false">
            Actions
          </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="<%= division_new_path %>">Add Division</a></li>
              <li><a class="dropdown-item" href="<%= designation_new_path %>">Add Designation</a></li>
              <li><a class="dropdown-item" href="<%= new_employee_registration_path %>">Add Employee</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="<%= employees_list_path %>">View Employees</a></li>
              <li><a class="dropdown-item" href="<%= division_index_path %>">View Divisions</a></li>
              <li><a class="dropdown-item" href="<%= designation_index_path %>">View Designations</a></li>
            </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="https://www.paychex.com">Details</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
<div class="container">
<div class="p-5 rounded-lg m-3", style="background: rgba(255, 255, 255, 0.8)">
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Designation Id</th>
      <th scope="col">Name</th>
      <th scope="colgroup">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @designations.each do |designation| %>
    <tr>
      <th scope="row"><%= designation.id %></th>
      <td><%= designation.name %></td>
      <td><a href="<%= designation_path(designation) %>" class="btn btn-outline-primary">Show</a>
          <a href="<%= designation_edit_path(designation) %>" class="btn btn-outline-primary">Edit</a>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<center><p><a href="<%= employee_root_path %>" class="btn btn-outline-primary">Back to Dashboard</a></p></center>
</div>
</div>
</div>

app/views/designations/new.html.erb
<div style="background-image: url(<%=asset_url('annie-spratt-FSFfEQkd1sc-unsplash.jpg')%>);background-size: cover;height: 100vh;">
<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
    <div class="container-fluid">
      <div class="navbar-brand">Employee Portal</div>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="https://www.paychex.com">Details</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>   

<div class="container">
<div class="p-5 rounded-lg m-3", style="background: rgba(255, 255, 255, 0.8)">
<center>
<h1>Create New Designation</h1> <br/>

<%= form_with model: @designation, local: true do |f| %>
    <p>
        <%= f.label :name %><br/>
        <%= f.text_field :name %>
    </p>  

    <p>
        <%= f.submit %>
    </p>
<% end %> 

</center>
<center><p><a href="<%= employee_root_path %>" class="btn btn-outline-primary">Cancel</a></p></center>
</div>
</div>
</div>

app/views/designations/show.html.erb
<div style="background-image: url(<%=asset_url('annie-spratt-FSFfEQkd1sc-unsplash.jpg')%>);background-size: cover;height: 100vh;">
<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
    <div class="container-fluid">
      <div class="navbar-brand">Employee Portal</div>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" id="navbarDropdown" data-bs-toggle="dropdown" aria-expanded="false">
            Actions
          </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="<%= division_new_path %>">Add Division</a></li>
              <li><a class="dropdown-item" href="<%= designation_new_path %>">Add Designation</a></li>
              <li><a class="dropdown-item" href="<%= new_employee_registration_path %>">Add Employee</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="<%= employees_list_path %>">View Employees</a></li>
              <li><a class="dropdown-item" href="<%= division_index_path %>">View Divisions</a></li>
              <li><a class="dropdown-item" href="<%= designation_index_path %>">View Designations</a></li>
            </ul>
          </li>  
          <li class="nav-item">
            <a class="nav-link" href="https://www.paychex.com">Details</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>   

<div class="container">
<div class="p-5 rounded-lg m-3", style="background: rgba(255, 255, 255, 0.8)">
<center>

<h1 class="display-4">Designation Details</h1> <br/>
<h3 class="display-7"><u>Name:</u> <%= @designation.name %></h3><br/>

<h4 class="display-6">Employees in the Designation</h4> <br/>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Employee Id</th>
      <th scope="col">Name</th>
      <th scope="col">Username</th>
      <th scope="col">Email</th>
      <th scope="colgroup">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @designation.employees.each do |employee| %>
    <tr>
      <th scope="row"><%= employee.id %></th>
      <td><%= employee.name %></td>
      <td><%= employee.username %></td>
      <td><%= employee.email %></td>
      <td><% unless current_employee==employee %>
            <a href="<%= employee_registration_edit_path(employee) %>" class="btn btn-outline-primary">Edit</a>
          <% end %>
      </td>    
    </tr>
    <% end %>
  </tbody>
</table>


</center>
<center><p><a href="<%= designation_index_path %>" class="btn btn-outline-primary">Back to Designations</a></p></center>
</div>
</div>
</div>