config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  
  # root route
  root "pages#index"

  # devise routes
  devise_for :employees, module: "employees", skip: [:registerations, :confirmations, :omniauth_callbacks] 
  as :employee do 
    get 'employee/edit/:id', to: "employees/registrations#edit", as: 'employee_registration_edit'
    patch '/employees/edit/:id', to: 'employees/registrations#update', as: 'employee_update'
    put '/employees/edit/:id', to: 'employees/registrations#update'

    get 'employee/profile/edit/:id', to: "employees/registrations#edit_profile", as: 'employee_registration_profile_edit'
    patch '/employees/profile/edit/:id', to: 'employees/registrations#update_profile', as: 'employee_profile_update'
    put '/employees/profile/edit/:id', to: 'employees/registrations#update_profile'
  end  

  # get routes
  get '/employee', to: "pages#dashboard", :as => :employee_root
  get '/employee/list', to: "pages#show", as: 'employees_list'

  get '/employee/division/new', to: "divisions#new", as: 'division_new'
  get '/employee/division/index', to: "divisions#index", as: 'division_index'
  get '/employee/division/edit/:id', to: 'divisions#edit', as: 'division_edit'
  get '/employee/division/show/:id', to: "divisions#show", as: 'division' 

  get '/employee/designation/new', to: "designations#new", as: 'designation_new'
  get '/employee/designation/index', to: "designations#index", as: 'designation_index'
  get '/employee/designation/edit/:id', to: 'designations#edit', as: 'designation_edit' 
  get '/employee/designation/show/:id', to: "designations#show", as: 'designation'

  get '/employee/project/new', to: "projects#new", as: 'project_new'
  get '/employee/project/index', to: "projects#index", as: 'project_index'
  get '/employee/project/edit/:id', to: "projects#edit", as: 'project_edit'
  get '/employee/project/show/:id', to: "projects#show", as: 'project' 
  get 'employee/project/assign/:id', to: "projects#assign_to_project", as: 'project_assign'
  get 'employee/project/remove/:id', to: "projects#remove_from_project", as: 'project_remove'

  # post put patch routes
  post 'designations', to: 'designations#create'
  patch '/designations/:id', to: 'designations#update', as: 'designation_update'
  put '/designations/:id', to: 'designations#update'

  post 'divisions', to: 'divisions#create'
  patch  '/divisions/:id', to: 'divisions#update', as: 'division_update'
  put   '/divisions/:id', to: 'divisions#update'

  post 'projects', to: 'projects#create'
  patch  '/projects/:id', to: 'projects#update', as: 'project_update'
  put   '/projects/:id', to: 'projects#update'
  post 'projects/assign/:id', to: 'projects#assign', as: 'project_assign_to' 

  # delete routes
  delete 'projects/remove/:id', to: 'projects#remove', as: 'project_remove_from'

end

app/views/pages/_employee.html.erb
<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
    <li><hr class="dropdown-divider"></li>
    <li><a class="dropdown-item" href="<%= project_index_path %>">View Projects</a></li>
</ul>

app/views/pages/_hr_manager.html.erb
<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
    <li><a class="dropdown-item" href="<%= division_new_path %>">Add Division</a></li>
    <li><a class="dropdown-item" href="<%= designation_new_path %>">Add Designation</a></li>
    <li><a class="dropdown-item" href="<%= new_employee_invitation_path %>">Add Employee</a></li>
    <li><hr class="dropdown-divider"></li>
    <li><a class="dropdown-item" href="<%= employees_list_path %>">View Employees</a></li>
    <li><a class="dropdown-item" href="<%= division_index_path %>">View Divisions</a></li>
    <li><a class="dropdown-item" href="<%= designation_index_path %>">View Designations</a></li>
</ul>

app/views/pages/_project_manager.html.erb
<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
    <li><a class="dropdown-item" href="<%= project_new_path %>">Add Project</a></li>
    <li><a class="dropdown-item" href="<%= project_assign_path(Project) %>">Assign to Project</a></li>
    <li><a class="dropdown-item" href="<%= project_remove_path(Project) %>">Remove from Project</a></li> 
    <li><hr class="dropdown-divider"></li>
    <li><a class="dropdown-item" href="<%= project_index_path %>">View Projects</a></li>
    <li><a class="dropdown-item" href="<%= employees_list_path %>">View Employees</a></li>
</ul>

app/views/pages/dashboard.html.erb
<div style="background-image: url(<%=asset_url('annie-spratt-FSFfEQkd1sc-unsplash.jpg')%>);background-size: cover;height: 100vh;">
<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
  <div class="container-fluid">
    <div class="navbar-brand">Employee Portal</div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" id="navbarDropdown" data-bs-toggle="dropdown" aria-expanded="false">
            Actions
          </a>
          <% case @employee %>
          <% when "HR Manager" %>
              <%= render "hr_manager" %>                  
          <% when "Project Manager" %>
              <%= render "project_manager" %>
          <% when "Employee" %>
              <%= render "employee" %>
          <% else %>
              <%= flash[:alert] = "You must be logged in to access this section" %>
              <% redirect_to root_path  %>    
          <% end %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="https://www.paychex.com">Details</a>
        </li>
        <li class="nav-item" style="margin-top:5px;margin-left:15px;">
           <%= button_to '<i class="icon-ok icon-white" aria-current="page"></i>Sign Out'.html_safe, destroy_employee_session_path, method: :delete %>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
    <div class="p-5 rounded-lg m-3", style="background: rgba(255, 255, 255, 0.9)">
      <h1 class="display-4">Personal Details</h1>

      <p class="lead">Name: <%= current_employee.name %><br/>
                      Employee Id: <%= current_employee.id %><br/>
                      Username: <%= current_employee.username %><br/>
                      Email: <%= current_employee.email %><br/>
                      Designation: <%= current_employee.designation.name %><br/>
                      Division: <%= current_employee.division.name %></p>
      <hr class="my-4">
      <p class="lead">Projects: <% unless current_employee.projects.empty? %>
                                  <% current_employee.projects.each do |project| %>
                                    <%= project.name %>
                                  <% end %>  
                                <% else %>
                                  None
                                <% end %></p>

      <% if @employee=="HR Manager" %>
        <div>
          <a href="<%= employee_registration_profile_edit_path(current_employee) %>" class="btn btn-outline-primary">Edit</a>
        </div><br/> 
      <% end %>    

      <div><a href="<%= employee_registration_edit_path(current_employee) %>" class="btn btn-outline-primary">Change Password</a></div>                        
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<div style="background-image: url(<%=asset_url('annie-spratt-FSFfEQkd1sc-unsplash.jpg')%>);background-size: cover;height: 100vh;">
  <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
    <div class="container-fluid">
      <div class="navbar-brand">Employee Portal</div>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="https://www.paychex.com">Details</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    <div class="p-5 rounded-lg m-3", style="background: rgba(255, 255, 255, 0.8)">
      <h1 class="display-4">PAYCHEX</h1>
      <p class="lead">One Employee Portal for evreyone and everything.</p>
      <hr class="my-4">
      <p>Just hop on to the login page for the best employee experience all in one, easy to use, always accessible, personal and detailed experience.</p>
    </div>
  </div>

  <%= render 'devise/sessions/new' %>
</div>

app/views/pages/show.html.erb
<div style="background-image: url(<%=asset_url('annie-spratt-FSFfEQkd1sc-unsplash.jpg')%>);background-size: cover;height: 100vh;">
<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
  <div class="container-fluid">
    <div class="navbar-brand">Employee Portal</div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="https://www.paychex.com">Details</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
<div class="p-5 rounded-lg m-3", style="background: rgba(255, 255, 255, 0.9)">
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Employee Id</th>
      <th scope="col">Name</th>
      <th scope="col">Username</th>
      <th scope="col">Email</th>
      <th scope="col">Designation</th>
      <th scope="col">Division</th>
      <th scope="col">Projects</th>
      <th scope="colgroup">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @employees.each do |employee| %>
    <tr>
      <th scope="row"><%= employee.id %></th>
      <td><%= employee.name %></td>
      <td><%= employee.username %></td>
      <td><%= employee.email %></td>
      <td><%= employee.designation.name %></td>
      <td><%= employee.division.name %></td>
      <td><% unless employee.projects.empty? %>
            <% current_employee.projects.each do |project| %>
              <%= project.name %>
            <% end %>  
          <% else %>
            None
          <% end %>  
      </td>
      <td style="width:16%"><% if @employee=="HR Manager" %>
            <% unless employee.master_role.name=="HR Manager" %>
              <a href="<%= employee_registration_profile_edit_path(employee) %>" class="btn btn-outline-primary">Edit</a>
            <% end %>
          <% elsif @employee=="Project Manager" %>
            <% unless employee.master_role.name=="Project Manager" %>
              <a href="<%= project_assign_path(Project) %>" class="btn btn-outline-primary">Assign</a>
              <a href="<%= project_remove_path(Project) %>" class="btn btn-outline-primary">Remove</a>
            <% end %>
          <% end %>  
      </td>    
    </tr>
    <% end %>
  </tbody>
</table>
<center><p>
<a href="<%= employee_root_path %>" class="btn btn-outline-primary">Back to Dashboard</a> 
</p></center>
</div>
</div>
</div>