config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  
  # root route
  root "pages#index"

  # devise routes
  devise_for :employees, module: "employees", skip: [:registerations, :confirmations, :omniauth_callbacks] 
  as :employee do 
    get 'employee/edit/:id', to: "employees/registrations#edit", as: 'employee_registration_edit'
    patch '/employees/edit/:id', to: 'employees/registrations#update', as: 'employee_update'
    put '/employees/edit/:id', to: 'employees/registrations#update'

    get 'employee/profile/edit/:id', to: "employees/registrations#edit_profile", as: 'employee_registration_profile_edit'
    patch '/employees/profile/edit/:id', to: 'employees/registrations#update_profile', as: 'employee_profile_update'
    put '/employees/profile/edit/:id', to: 'employees/registrations#update_profile'
  end  

  # get routes
  get '/employee', to: "pages#dashboard", :as => :employee_root
  get '/employee/list', to: "pages#show", as: 'employees_list'

  get '/employee/division/new', to: "divisions#new", as: 'division_new'
  get '/employee/division/index', to: "divisions#index", as: 'division_index'
  get '/employee/division/edit/:id', to: 'divisions#edit', as: 'division_edit'
  get '/employee/division/show/:id', to: "divisions#show", as: 'division' 

  get '/employee/designation/new', to: "designations#new", as: 'designation_new'
  get '/employee/designation/index', to: "designations#index", as: 'designation_index'
  get '/employee/designation/edit/:id', to: 'designations#edit', as: 'designation_edit' 
  get '/employee/designation/show/:id', to: "designations#show", as: 'designation'

  get '/employee/project/new', to: "projects#new", as: 'project_new'
  get '/employee/project/index', to: "projects#index", as: 'project_index'
  get '/employee/project/edit/:id', to: "projects#edit", as: 'project_edit'
  get '/employee/project/show/:id', to: "projects#show", as: 'project' 
  get 'employee/project/assign/:id', to: "projects#assign_to_project", as: 'project_assign'
  get 'employee/project/remove/:id', to: "projects#remove_from_project", as: 'project_remove'

  # post put patch routes
  post 'designations', to: 'designations#create'
  patch '/designations/:id', to: 'designations#update', as: 'designation_update'
  put '/designations/:id', to: 'designations#update'

  post 'divisions', to: 'divisions#create'
  patch  '/divisions/:id', to: 'divisions#update', as: 'division_update'
  put   '/divisions/:id', to: 'divisions#update'

  post 'projects', to: 'projects#create'
  patch  '/projects/:id', to: 'projects#update', as: 'project_update'
  put   '/projects/:id', to: 'projects#update'
  post 'projects/assign/:id', to: 'projects#assign', as: 'project_assign_to' 

  # delete routes
  delete 'projects/remove/:id', to: 'projects#remove', as: 'project_remove_from'

end

app/models/project.rb
class Project < ApplicationRecord

   ## Validations
   validates :name, presence: true, length: { minimum: 2, maximum: 50 }, uniqueness: { case_sensitive: false }
   validates :description, presence: true, length: { minimum: 6, maximum: 400 } 
   
   ## Associations
   has_many :teams, dependent: :destroy
   has_many :employees, through: :teams

end   

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :identify_if_manager, except: [:index, :show]
    before_action :identify_employee, only: [:index, :show]

    def index 
        @projects = Project.all
    end    

    def new 
        @project = Project.new
    end  
    
    def show 
        @project = Project.find(params[:id])
    end 

    def create 
        @project = Project.new(params.require(:project).permit(:name, :description))
        if @project.save
            flash[:notice] = "Project was successfully created."
            redirect_to project_path(@project)
        else 
            render 'new'    
        end    
    end  
    
    def edit
        @project = Project.find(params[:id])
    end 

    def update 
        @project = Project.new(params.require(:project).permit(:name, :description))
        if @project.update
            flash[:notice] = "Project was successfully updated."
            redirect_to project_path(@project)
        else 
            render 'edit'    
        end    
    end 

    def assign_to_project  
        @projects = Project.all
        if ( params[:id] != "Project" ) 
            @project = Project.find(params[:id])
            @employees = Employee.all.reject{|employee| employee.projects.include?Project.first}
        end
    end   

    def assign
        @project = Project.find(params[:id])
        employee = Employee.find(params[:employee_id]) 
        if team = Team.create(project_id: @project.id, employee_id: employee.id)
            flash[:notice] = "Successfully Assigned"
            redirect_to project_assign_path(@project)
        else 
            render 'assign_to_project'    
        end    
    end    
    
    def remove_from_project  
        @projects = Project.all
        if ( params[:id] != "Project" ) 
            @project = Project.find(params[:id])
            @employees = Employee.all.select{|employee| employee.projects.include?Project.first}
        end
    end    

    def remove 
        project_id = params[:id]
        team = Team.find_by(params[:employee_id], project_id)
        # team = Team.all.select{|team| team.project_id == @project.id && team.employee_id == employee.id}
        team.destroy
        redirect_to project_remove_path(project_id)
    end    

    private

    def identify_if_manager
        unless current_employee.master_role.name == "Project Manager"
            flash[:alert] = "You do not have access to this section" 
            redirect_to employee_root_path 
        end 
    end 

    def identify_employee 
        unless current_employee.master_role.name == "Project Manager" || current_employee.master_role.name == "Employee"
            flash[:alert] = "You do not have access to this section" 
            redirect_to employee_root_path 
        end 
    end 

end  

app/views/projects/assign_to_project.html.erb
<div style="background-image: url(<%=asset_url('annie-spratt-FSFfEQkd1sc-unsplash.jpg')%>);background-size: cover;height: 100vh;">
<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
  <div class="container-fluid">
    <div class="navbar-brand">Employee Portal</div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <% if current_employee.master_role.name == "Project Manager" %>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" id="navbarDropdown" data-bs-toggle="dropdown" aria-expanded="false">
              Actions
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="<%= project_new_path %>">Add Project</a></li>
              <li><a class="dropdown-item" href="<%= project_assign_path(Project) %>">Assign to Project</a></li>
              <li><a class="dropdown-item" href="<%= project_remove_path(Project) %>">Remove from Project</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="<%= project_index_path %>">View Projects</a></li>
              <li><a class="dropdown-item" href="<%= employees_list_path %>">View Employees</a></li>
            </ul>
        </li>  
      <% end %>  
        <li class="nav-item">
          <a class="nav-link" href="https://www.paychex.com">Details</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
<div class="p-5 rounded-lg m-3", style="background: rgba(255, 255, 255, 0.8)">
<center>
<h1>Select a Project</h1> <br/>

<% if current_employee.master_role.name == "Project Manager" %>
  <div class="dropdown-center">
    <button class="btn btn-secondary btn-lg dropdown-toggle bg-primary" style="width:400px;" type="button" data-bs-toggle="dropdown" aria-expanded="false">
      Select a Project
    </button>
    <ul class="dropdown-menu">
      <% @projects.each do |project| %>
        <li><a class="dropdown-item" href="<%= project_assign_path(:id => project) %>"><%= project.name %></a></li>
      <% end %>
    </ul>
  </div><br/>         
<% end %>

<% if params[:id] != "Project" %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Employee Id</th>
        <th scope="col">Name</th>
        <th scope="col">Username</th>
        <th scope="col">Email</th>
        <th scope="col">Designation</th>
        <th scope="col">Division</th>
        <th scope="colgroup">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @employees.each do |employee| %>
        <tr>
          <th scope="row"><%= employee.id %></th>
          <td><%= employee.name %></td>
          <td><%= employee.username %></td>
          <td><%= employee.email %></td>
          <td><%= employee.designation.name %></td>
          <td><%= employee.division.name %></td>
          <td><%= button_to 'Add', project_assign_to_path(@project, :employee_id => employee), method: :post %></td>
        </tr>
      <% end %>  
    </tbody>
  </table>    
<% end %> <br/>

<p><a href="<%= employee_root_path %>" data-method="post" class="btn btn-outline-primary">Back to Dashboard</a></p>
</center>
</div>
</div>
</div>

app/views/projects/edit.html.erb
<div style="background-image: url(<%=asset_url('annie-spratt-FSFfEQkd1sc-unsplash.jpg')%>);background-size: cover;height: 100vh;">
<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
    <div class="container-fluid">
      <div class="navbar-brand">Employee Portal</div>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="https://www.paychex.com">Details</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>   

<div class="container">
<div class="p-5 rounded-lg m-3", style="background: rgba(255, 255, 255, 0.8)">
<center>
<h1>Create New Project</h1> <br/>

<%= form_with model: @project, local: true do |f| %>
    <p>
        <%= f.label :name %><br/>
        <%= f.text_field :name %>
    </p>  

    <p>
        <%= f.label :description %><br/>
        <%= f.text_area :description %>
    </p>  

    <p>
        <%= f.submit %>
    </p>
<% end %> 

</center>
<center><p><a href="<%= project_index_path %>" class="btn btn-outline-primary">Cancel</a></p></center>
</div>
</div>
</div>

app/views/projects/index.html.erb
<div style="background-image: url(<%=asset_url('annie-spratt-FSFfEQkd1sc-unsplash.jpg')%>);background-size: cover;height: 100vh;">
<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
  <div class="container-fluid">
    <div class="navbar-brand">Employee Portal</div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <% if current_employee.master_role.name == "Project Manager" %>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" id="navbarDropdown" data-bs-toggle="dropdown" aria-expanded="false">
              Actions
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="<%= project_new_path %>">Add Project</a></li>
              <li><a class="dropdown-item" href="<%= project_assign_path(Project) %>">Assign to Project</a></li>
              <li><a class="dropdown-item" href="<%= project_remove_path(Project) %>">Remove from Project</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="<%= project_index_path %>">View Projects</a></li>
              <li><a class="dropdown-item" href="<%= employees_list_path %>">View Employees</a></li>
            </ul>
        </li>  
      <% end %>  
        <li class="nav-item">
          <a class="nav-link" href="https://www.paychex.com">Details</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
<div class="p-5 rounded-lg m-3", style="background: rgba(255, 255, 255, 0.8)">
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Project Id</th>
      <th scope="col">Name</th>
      <th scope="col">Description</th>
      <th scope="colgroup">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% if current_employee.master_role.name == "Project Manager" %>
      <% @projects.each do |project| %>
      <tr>
        <th scope="row"><%= project.id %></th>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td style="width:12%"><a href="<%= project_path(project) %>" class="btn btn-outline-primary">Show</a>
              <a href="<%= project_edit_path(project) %>" class="btn btn-outline-primary">Edit</a>
        </td>
      </tr>
      <% end %>
    <% else %>
      <% current_employee.projects.each do |project| %>
      <tr>
        <th scope="row"><%= project.id %></th>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td style="width:12%"><a href="<%= project_path(project) %>" class="btn btn-outline-primary">Show</a>
        </td>
      </tr>  
      <% end %>
    <% end %>
  </tbody>
</table>
<center><p><a href="<%= employee_root_path %>" class="btn btn-outline-primary">Back to Dashboard</a></p></center>
</div>
</div>
</div>

app/views/projects/new.html..erb
<div style="background-image: url(<%=asset_url('annie-spratt-FSFfEQkd1sc-unsplash.jpg')%>);background-size: cover;height: 100vh;">
<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
    <div class="container-fluid">
      <div class="navbar-brand">Employee Portal</div>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="https://www.paychex.com">Details</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>   

<div class="container">
<div class="p-5 rounded-lg m-3", style="background: rgba(255, 255, 255, 0.8)">
<center>
<h1>Create New Project</h1> <br/>

<%= form_with model: @project, local: true do |f| %>
    <p>
        <%= f.label :name %><br/>
        <%= f.text_field :name %>
    </p>  

    <p>
        <%= f.label :description %><br/>
        <%= f.text_area :description %>
    </p>  

    <p>
        <%= f.submit %>
    </p>
<% end %> 

</center>
<center><p><a href="<%= employee_root_path %>" class="btn btn-outline-primary">Cancel</a></p></center>
</div>
</div>
</div>

app/views/projects/new.html.erb
<div style="background-image: url(<%=asset_url('annie-spratt-FSFfEQkd1sc-unsplash.jpg')%>);background-size: cover;height: 100vh;">
<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
    <div class="container-fluid">
      <div class="navbar-brand">Employee Portal</div>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="https://www.paychex.com">Details</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>   

<div class="container">
<div class="p-5 rounded-lg m-3", style="background: rgba(255, 255, 255, 0.8)">
<center>
<h1>Create New Project</h1> <br/>

<%= form_with model: @project, local: true do |f| %>
    <p>
        <%= f.label :name %><br/>
        <%= f.text_field :name %>
    </p>  

    <p>
        <%= f.label :description %><br/>
        <%= f.text_area :description %>
    </p>  

    <p>
        <%= f.submit %>
    </p>
<% end %> 

</center>
<center><p><a href="<%= employee_root_path %>" class="btn btn-outline-primary">Cancel</a></p></center>
</div>
</div>
</div>

app/views/projects/remove_from_project.html.erb
<div style="background-image: url(<%=asset_url('annie-spratt-FSFfEQkd1sc-unsplash.jpg')%>);background-size: cover;height: 100vh;">
<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
  <div class="container-fluid">
    <div class="navbar-brand">Employee Portal</div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <% if current_employee.master_role.name == "Project Manager" %>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" id="navbarDropdown" data-bs-toggle="dropdown" aria-expanded="false">
              Actions
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="<%= project_new_path %>">Add Project</a></li>
              <li><a class="dropdown-item" href="<%= project_assign_path(Project) %>">Assign to Project</a></li>
              <li><a class="dropdown-item" href="<%= project_remove_path(Project) %>">Remove from Project</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="<%= project_index_path %>">View Projects</a></li>
              <li><a class="dropdown-item" href="<%= employees_list_path %>">View Employees</a></li>
            </ul>
        </li>  
      <% end %>  
        <li class="nav-item">
          <a class="nav-link" href="https://www.paychex.com">Details</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

<div class="container">
<div class="p-5 rounded-lg m-3", style="background: rgba(255, 255, 255, 0.8)">
<center>
<h1>Select a Project</h1> <br/>

<% if current_employee.master_role.name == "Project Manager" %>
  <div class="dropdown-center">
    <button class="btn btn-secondary btn-lg dropdown-toggle bg-primary" style="width:400px;" type="button" data-bs-toggle="dropdown" aria-expanded="false">
      Select a Project
    </button>
    <ul class="dropdown-menu">
      <% @projects.each do |project| %>
        <li><a class="dropdown-item" href="<%= project_remove_path(:id => project) %>"><%= project.name %></a></li>
      <% end %>
    </ul>
  </div><br/>         
<% end %>

<% if params[:id] != "Project" %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">Employee Id</th>
        <th scope="col">Name</th>
        <th scope="col">Username</th>
        <th scope="col">Email</th>
        <th scope="col">Designation</th>
        <th scope="col">Division</th>
        <th scope="colgroup">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @employees.each do |employee| %>
        <tr>
          <th scope="row"><%= employee.id %></th>
          <td><%= employee.name %></td>
          <td><%= employee.username %></td>
          <td><%= employee.email %></td>
          <td><%= employee.designation.name %></td>
          <td><%= employee.division.name %></td>
          <td><%= button_to 'Remove', project_remove_from_path(@project, :employee_id => employee), method: :delete, data: { turbo_confirm: "Are you sure?" } %></td>
        </tr>
      <% end %>  
    </tbody>
  </table>    
<% end %> <br/>

<p><a href="<%= employee_root_path %>" class="btn btn-outline-primary">Back to Dashboard</a></p>
</center>
</div>
</div>
</div>

app/views/projects/show.html.erb
<div style="background-image: url(<%=asset_url('annie-spratt-FSFfEQkd1sc-unsplash.jpg')%>);background-size: cover;height: 100vh;">
<nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
    <div class="container-fluid">
      <div class="navbar-brand">Employee Portal</div>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if current_employee.master_role.name == "Project Manager" %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" id="navbarDropdown" data-bs-toggle="dropdown" aria-expanded="false">
              Actions
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="<%= project_new_path %>">Add Project</a></li>
              <li><a class="dropdown-item" href="<%= project_assign_pat(Project) %>">Assign to Project</a></li>
              <li><a class="dropdown-item" href="<%= project_remove_pat %>">Remove from Project</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="<%= project_index_path %>">View Projects</a></li>
              <li><a class="dropdown-item" href="<%= employees_list_path %>">View Employees</a></li>
            </ul>
          </li>  
        <% end %>  
          <li class="nav-item">
            <a class="nav-link" href="https://www.paychex.com">Details</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>   

<div class="container">
<div class="p-5 rounded-lg m-3", style="background: rgba(255, 255, 255, 0.8)">
<center>

<h1 class="display-4">Project Details</h1> <br/>
<h3 class="display-7"><u>Name:</u> <%= @project.name %></h3>
<h5 class="display-7"><u>Description:</u> <%= @project.description %></h5><br/>

<h4 class="display-6">Employees in the Project</h4> <br/>
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Employee Id</th>
      <th scope="col">Name</th>
      <th scope="col">Username</th>
      <th scope="col">Email</th>
    </tr>
  </thead>
  <tbody>
    <% @project.employees.each do |employee| %>
    <tr>
      <th scope="row"><%= employee.id %></th>
      <td><%= employee.name %></td>
      <td><%= employee.username %></td>
      <td><%= employee.email %></td>  
    </tr>
    <% end %>
  </tbody>
</table>


</center>
<center><p><a href="<%= project_index_path %>" class="btn btn-outline-primary">Back to Projects</a></p></center>
</div>
</div>
</div>